"""Compatibility facade for the pure recovered object semantics.

New code should import from ``game.objects.lifecycle`` or
``game.objects.collection``. Existing boundary adapters, tests and user
scripts may continue importing this module while the semantic package is
organized by object family.
"""

from .game.objects.collection import collection_state, increment_counter
from .game.objects.contact import (activate_contact, begin_contact_launch, finish_contact_launch,
                                   contact_decay, contact_path, contact_reaction, contact_reset,
                                   contact_route, contact_repeated_decay, contact_sibling_route,
                                   contact_type78_route,
                                   contact_script_selector, transition_contact_66, transition_contact_6b,
                                   publish_contact_record, transition_contact_77, finish_contact_type7e)
from .game.objects.contact import contact_scan_collision
from .game.rng import advance_rng, rng_writes
from .game.objects.contact import (contact_type55_guard, contact_type55_return,
                                   contact_type46_request, contact_type43_update)
from .game.objects.contact import (contact_type58_guard, contact_type58_fail,
                                   contact_type58_pass)
from .game.objects.contact import (contact_type63_guard, contact_type63_fail,
                                   contact_type63_pass, contact_type63_retype)
from .game.objects.contact import (contact_type74_guard, contact_type74_fail,
                                   contact_type74_pass, contact_type74_target,
                                   contact_type74_retype, contact_type74_position)
from .game.objects.contact import (contact_type6e_guard, contact_type6e_fail,
                                   contact_type6e_pass, contact_type6e_reinit)
from .game.objects.contact import contact_type23_retype, contact_type23_override
from .game.objects.contact import contact_tick_reset, contact_tick_bounds
from .game.objects.contact import (complete_contact_landing, publish_contact_position,
                                   contact_landing_script, contact_position)
from .game.objects.lifecycle import (
    activate_collection,
    clear_pair,
    finish_reverse_spawn,
    finish_primary_double_guard_spawn,
    finish_primary_inverse_guard_spawn,
    finish_primary_mixed_guard_spawn,
    finish_upper_dispatch_spawn,
    finish_upper_spawn,
    finish_upper_variant_spawn,
    finish_upper_scripted_spawn,
    finish_upper_typed_spawn,
    reset_lower_spawn_flag,
    finish_lower_scripted_spawn,
    finish_type_8a_spawn,
    finish_type_41_spawn,
    finish_type_84_spawn,
    finish_type_4c_spawn,
    finish_guarded_lower_spawn,
    finish_reverse_script_spawn,
    finish_lower_offset_spawn,
    finish_upper_tile_word_spawn,
    finish_reverse_script_a_spawn,
    finish_reverse_script_b_spawn,
    finish_upper_type22_spawn,
    finish_guarded_lower_two_spawn,
    finish_guarded_lower_three_spawn,
    finish_reverse_script_c_spawn,
    finish_type_47_spawn,
    finish_type_6c_spawn,
    finish_guarded_lower_four_spawn,
    finish_guarded_lower_five_spawn,
    finish_type_1b_flag_spawn,
    finish_type_4b_spawn,
    finish_type_49_spawn,
    finish_type_48_spawn,
    finish_type_4a_spawn,
    finish_type_1a_offset_spawn,
    free_object,
    free_object_reverse,
    initialize,
    relocate_object,
    release_buffer,
    retire_collected_object,
    spawn_collection,
    spawn_region,
    select_spawn_dispatch_slot,
    offset_spawn_position,
    prepare_spawn_strip,
    unlink,
)

__all__ = [
    "activate_collection",
    "activate_contact",
    "contact_scan_collision",
    "advance_rng",
    "rng_writes",
    "contact_type55_guard",
    "contact_type55_return",
    "contact_type46_request",
    "contact_type43_update",
    "contact_type58_guard",
    "contact_type58_fail",
    "contact_type58_pass",
    "contact_type63_guard",
    "contact_type63_fail",
    "contact_type63_pass",
    "contact_type63_retype",
    "contact_type74_guard",
    "contact_type74_fail",
    "contact_type74_pass",
    "contact_type74_target",
    "contact_type74_retype",
    "contact_type74_position",
    "contact_type6e_guard",
    "contact_type6e_fail",
    "contact_type6e_pass",
    "contact_type6e_reinit",
    "contact_type23_retype",
    "contact_type23_override",
    "contact_tick_reset",
    "contact_tick_bounds",
    "begin_contact_launch",
    "finish_contact_launch",
    "transition_contact_66",
    "transition_contact_6b",
    "publish_contact_record",
    "transition_contact_77",
    "finish_contact_type7e",
    "complete_contact_landing",
    "contact_landing_script",
    "contact_position",
    "publish_contact_position",
    "clear_pair",
    "collection_state",
    "contact_decay",
    "contact_path",
    "contact_reaction",
    "contact_reset",
    "contact_route",
    "contact_repeated_decay",
    "contact_sibling_route",
    "contact_type78_route",
    "contact_script_selector",
    "finish_reverse_spawn",
    "finish_primary_double_guard_spawn",
    "finish_primary_inverse_guard_spawn",
    "finish_primary_mixed_guard_spawn",
    "finish_upper_dispatch_spawn",
    "finish_upper_spawn",
    "finish_upper_variant_spawn",
    "finish_upper_scripted_spawn",
    "finish_upper_typed_spawn",
    "reset_lower_spawn_flag",
    "finish_lower_scripted_spawn",
    "finish_type_8a_spawn",
    "finish_type_41_spawn",
    "finish_type_84_spawn",
    "finish_type_4c_spawn",
    "finish_guarded_lower_spawn",
    "finish_reverse_script_spawn",
    "finish_lower_offset_spawn",
    "finish_upper_tile_word_spawn",
    "finish_reverse_script_a_spawn",
    "finish_reverse_script_b_spawn",
    "finish_upper_type22_spawn",
    "finish_guarded_lower_two_spawn",
    "finish_guarded_lower_three_spawn",
    "finish_reverse_script_c_spawn",
    "finish_type_47_spawn",
    "finish_type_6c_spawn",
    "finish_guarded_lower_four_spawn",
    "finish_guarded_lower_five_spawn",
    "finish_type_1b_flag_spawn",
    "finish_type_4b_spawn",
    "finish_type_49_spawn",
    "finish_type_48_spawn",
    "finish_type_4a_spawn",
    "finish_type_1a_offset_spawn",
    "free_object",
    "free_object_reverse",
    "increment_counter",
    "initialize",
    "relocate_object",
    "release_buffer",
    "retire_collected_object",
    "spawn_collection",
    "spawn_region",
    "select_spawn_dispatch_slot",
    "offset_spawn_position",
    "prepare_spawn_strip",
    "unlink",
]
